### ISSUE TITLE
Consider rebase to a newer mozjs?

### ISSUE THREAD

**Issue by frantisekz** [erlang-mozjs/erlang-mozjs#6]
Would it be possible to get this package from a long-obsolete mozjs68 to a newer version? mozjs102 is the latest and would be ideal!

Thanks!

**Comment by lemenkov** [comment]
@frantisekz thanks for the heads up. I'll do it ASAP.

**Comment by frantisekz** [comment]
Thanks a lot!, would you also take care of Fedora package update?

**Comment by lemenkov** [comment]
> Thanks a lot!, would you also take care of Fedora package update?

Yes sure,

**Comment by frantisekz** [comment]
@lemenkov Just to let you know (in case you'd missed it), the updated Fedora build has failed.
